name: 2. Database Migration

on:
  workflow_run:
    workflows: ["1. Code Quality Checks"]
    types:
      - completed

jobs:
  db-migration:
    name: 🗄️ Database Migration
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 📥 Pull repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: ⚙️ Install Node.js v20 & configure npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: 📦 Strict installation from package-lock.json
        run: npm ci

      - name: 🗄️ Compare schema & apply changes to Neon Database
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: npx drizzle-kit push
